version: '3.8'

services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - ENV_VAR=value
    volumes:
      - ./data:/app/data
    restart: unless-stopped
