version: '3.8'
services:
  code-server:
    image: "codercom/code-server:latest"
    network_mode: host
    environment:
      - TZ=${TZ}
      - email=${EMAIL}
      - password=${PASSWORD}
      - DOCKER_USER=${USER}
      - domainname=${SUBDOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coder:/home/coder/
    restart: unless-stopped
