version: '3.8'
services:
  code-server:
    image: "codercom/code-server:latest"
    network_mode: host
    environment:
      - TZ=${TZ}
      - email=${EMAIL}
      - password=${PASSWORD}
      - domainname=${SUBDOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./coder:/home/coder/
      - ./entrypount.d:/entrypoint.d
    restart: unless-stopped
